version: '3.3'
services:
  web:
    build:
      context: ./
    volumes:
      - .:/src
      - /src/node_modules
    command: supervisor -e 'js,pug,html' index.js
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=sd2-db
      - DB_PORT=3306

  db:
    image: mysql
    restart: always
    env_file:
      - ./.env
    ports:
      - "3308:3306"
    volumes:
      - ./db:/var/lib/mysql
      - ./docker/init/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    env_file:
      - ./.env
    ports:
      - "8081:80"